### ISSUE TITLE
他プレイヤーのanimator controllerの作成

### ISSUE THREAD

**Issue by snct-ukai** [GTO-GamblerTeacherOka/VIRCE#41]
位置情報に更新があった場合にアニメーションを付ける
GameObjectのanimator componentの設定は `Assets/scripts/VRoid/ModelManager.cs`で完了しているためアニメーションの切り替えのみに責任を持つクラスを作成する
animatorの使い方は `Assets/scripts/Lobby/PlayerControl.cs`を参考にしてください

**Comment by maesuke269** [comment]
その場歩きを直さないと

**Comment by maesuke269** [comment]
現状分かるバグ
・他のユーザのアバターのアニメーションが足を怪我したみたいに片足を引きずってる(もう片足を出すモーションが再生出来ていない？)
・unityが異常終了したときに残ったアバターがその場歩きする

**Comment by snct-ukai** [comment]
後者はクライアント側ではどうしようもないので仕様にします
前者はアニメーションが遅延とかで位置が変わってないと判断されて、変わった瞬間にまたリスタートしてしまってるので、複数フレームで位置が変わらなかったら停止とかにしたらいい感じになるかも？
停止判定で余裕持たせるなら小数型から整数型へのキャストで生じる桁落ち誤差を使うことがよくあるかな（小数第一位までみたいならfloat変数を10倍したものをintにキャストして比較、みたいな）
