### ISSUE TITLE
ビルドするとチャットが送信できなくなる

### ISSUE THREAD

**Issue by snct-ukai** [GTO-GamblerTeacherOka/VIRCE#63]
ボタンの判定が消えてしまってるので要調査
レイヤーの重なり方的な問題かもしれない

**Comment by maesuke269** [comment]
<img width="642" alt="image" src="https://github.com/GTO-GamblerTeacherOka/VIRCE/assets/108317162/ad2ae0c0-7e16-4eb5-a132-69a642817e26">
とりあえずこれくらい送信ボタンを離しても送信ができない。
テキストボックスに判定を吸われているわけでは無さそうか

**Comment by snct-ukai** [comment]
そうなるとボタンの画像に問題がある可能性もあるから別の素材に差し替えをしてみて、unity editor上でできる

**Comment by maesuke269** [comment]
![yajirushi04_hayai](https://github.com/GTO-GamblerTeacherOka/VIRCE/assets/108317162/ba7d078a-5483-4961-a13a-4c9e387dd50a)

いらすとやから引っ張ってきたものを使ってみたけどこれもダメだった。
pngがダメか？と思ったけど他のチャット周りのボタンもpngだから画像ファイル形式の問題では無いのかな

**Comment by maesuke269** [comment]
ペイントでjpgの画像作ってやってみたけどこれもうまく行かず

**Comment by snct-ukai** [comment]
もしかしたら処理途中でエラーが発生して表示の処理までに関数が中断されてる可能性あるかも
何かの方法でエラーメッセージを見れるようにして確認してみて（テキスト表示のオブジェクト置いたりとか）

**Comment by maesuke269** [comment]
<img width="807" alt="image" src="https://github.com/GTO-GamblerTeacherOka/VIRCE/assets/108317162/ffa87520-0a21-42ed-a547-885c877a66fe">

見れた

**Comment by maesuke269** [comment]
The type initializer for "Lobby.Chat.ChatManager"

**Comment by snct-ukai** [comment]
with #85
